const arr = [
    {
        'name': '1A',
        'info': [
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": "Ветеран ВОВ"},
        ]
    },
    {
        'name' : '1Б',
        'info': [
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
        ]
    },
    {
        'name' : '1В',
        'info': [
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
        ]
    },
    {
        'name' : '1Г',
        'info': [
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
        ]
    },
    {
        'name' : '1Д',
        'info': [
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
        ]
    },
    {
        'name' : '1Е',
        'info': [
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
        ]
    },
    {
        'name' : '2А',
        'info': [
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
        ]
    },
    {
        'name' : '2Б',
        'info': [
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
        ]
    },
    {
        'name' : '2В',
        'info': [
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
        ]
    },
    {
        'name' : '2Г',
        'info': [
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
        ]
    },
    {
        'name' : '2Д',
        'info': [
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
        ]
    },
    {
        'name' : '2Е',
        'info': [
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
            {"scr": "imgs/1.jpg", "text": ">Ветеран ВОВ"},
        ]
    }
];